version: "3.9"
name: cs453-test

services:
  postgres:
    image: postgres:16
    container_name: cs453-postgres-test
    restart: unless-stopped
    environment:
      POSTGRES_DB: cs453_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres-test-data:/var/lib/postgresql/data
      - ./apps/api/src/db/schema.sql:/docker-entrypoint-initdb.d/schema.test.sql

volumes:
  postgres-test-data:
